services:
    # Laravel Application
    app:
        # define the build context here, but NOT the target (see overrides)
        build:
            context: .
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        networks:
            - laravel
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        # ports:
        # define the generic internal mapping here
        # The external port (80 vs 8080) is handled in overrides
        # - "80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            # Nginx needs to see public files (we mount them differently in Dev vs Prod)
        networks:
            - laravel
        depends_on:
            - app

    # The Database
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_USER: ${DB_USERNAME}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10

    # The Cache
    redis:
        image: redis:alpine
        container_name: redis
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "9000:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - mysql
        networks:
            - laravel

    bugsink:
        image: bugsink/bugsink:2
        depends_on:
            mysql:
                condition: service_healthy
        restart: unless-stopped
        ports:
            - "8000:8000"
        environment:
            SECRET_KEY: LyUE4pBKSR9rp20/oWGbbeqbEJLUIrOoGhiSqQflFYpIX27Oh9WHAqxSNwnSWIwMK+w= # Change this (and remove django-insecure prefix), e.g. openssl rand -base64 50
            CREATE_SUPERUSER: admin:password # Change this (or remove it and execute 'createsuperuser' against the running container)
            PORT: 8000
            # DATABASE_URL: postgresql://bugsinkuser:your_super_secret_password@db:5432/bugsink # Change password to match POSTGRES_PASSWORD above
            DATABASE_URL: mysql://root:password@mysql:3306/bugsink # Change password to match POSTGRES_PASSWORD above
            BEHIND_HTTPS_PROXY: "false" # Change this for setups behind a proxy w/ ssl enabled
            BASE_URL: "http://bugsink:8000"
            # BASE_URL: "https://aungmoemt.site"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'python -c ''import requests; requests.get("http://localhost:8000/").raise_for_status()''',
                ]
            interval: 5s
            timeout: 20s
            retries: 10
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
